# Generated by Django 5.1.1 on 2024-09-08 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_job_detail'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoverForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('language_of_book', models.CharField(max_length=100)),
                ('editor', models.CharField(blank=True, max_length=100)),
                ('book_type', models.CharField(max_length=100)),
                ('isbn_number', models.CharField(max_length=100)),
            ],
        ),
    ]
